image: registry.gitlab.com/gitlab-org/terraform-images/branches/v1-6-0-1.3:f158d31c1356d14029d8285ddd4b79ebbe6d7e90

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}

cache:
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}
  - gitlab-terraform init -upgrade

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: apply
  allow_failure: false
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  only:
    - master
    - main
